import { defineConst } from "@/lib/utils";

const currencies = defineConst([
  { key: "AUD", symbol: "$" },
  { key: "BGN", symbol: "лв" },
  { key: "BRL", symbol: "R$" },
  { key: "CAD", symbol: "$" },
  { key: "CHF", symbol: "₣" },
  { key: "CNY", symbol: "¥" },
  { key: "CZK", symbol: "Kč" },
  { key: "DKK", symbol: "kr" },
  { key: "EUR", symbol: "€" },
  { key: "GBP", symbol: "£" },
  { key: "HKD", symbol: "$" },
  { key: "HUF", symbol: "Ft" },
  { key: "IDR", symbol: "Rp" },
  { key: "ILS", symbol: "₪" },
  { key: "INR", symbol: "₹" },
  { key: "ISK", symbol: "kr" },
  { key: "JPY", symbol: "¥" },
  { key: "KRW", symbol: "₩" },
  { key: "MXN", symbol: "$" },
  { key: "MYR", symbol: "RM" },
  { key: "NOK", symbol: "kr" },
  { key: "NZD", symbol: "$" },
  { key: "PHP", symbol: "₱" },
  { key: "PLN", symbol: "zł" },
  { key: "RON", symbol: "lei" },
  { key: "SEK", symbol: "kr" },
  { key: "SGD", symbol: "$" },
  { key: "THB", symbol: "฿" },
  { key: "TRY", symbol: "₺" },
  { key: "USD", symbol: "$" },
  { key: "ZAR", symbol: "R" },
] as const);

export default currencies;
