-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "description" SET DATA TYPE VARCHAR(64);

-- AlterTable
ALTER TABLE "Collection" ALTER COLUMN "description" SET DATA TYPE VARCHAR(64);

-- AlterTable
ALTER TABLE "Image" ALTER COLUMN "title" SET DATA TYPE VARCHAR(128),
ALTER COLUMN "slug" SET DATA TYPE VARCHAR(128),
ALTER COLUMN "name" SET DATA TYPE VARCHAR(132);

-- AlterTable
ALTER TABLE "Subcollection" ALTER COLUMN "title" SET DATA TYPE VARCHAR(32),
ALTER COLUMN "slug" SET DATA TYPE VARCHAR(32),
ALTER COLUMN "description" SET DATA TYPE VARCHAR(64);
