import type { Metadata } from "next";
import { Playfair_Display, Outfit } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const playfair_display = Playfair_Display({
  variable: "--font-playfair-display",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const outfit = Outfit({
  variable: "--font-outfit",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair_display.variable} ${outfit.variable} antialiased`}
      >
        <header className="w-full">
          <p className="bg-slate-300 py-2 text-center text-xs font-normal">
            Embrace Timeless Beauty ✨ Your Adventure, Our Adornments 💍 Every
            Experience Sparkles with Joy
          </p>
          <hgroup className="flex flex-row flex-wrap items-center justify-center px-4 sm:px-8 lg:px-16">
            <div className="w-1/2 lg:w-1/3"></div>
            <div className="w-1/2 lg:w-1/3"></div>
            <Link href="/" className="w-full lg:w-1/3">
              <h1 className="text-center text-3xl font-medium">App Title</h1>
            </Link>
          </hgroup>
        </header>
        {children}
      </body>
    </html>
  );
}
