import type { Metadata } from "next";
import { Playfair_Display, Outfit } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ChevronDown, Mail, Search, ShoppingBag } from "lucide-react";

const playfair_display = Playfair_Display({
  variable: "--font-playfair-display",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const outfit = Outfit({
  variable: "--font-outfit",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair_display.variable} ${outfit.variable} antialiased`}
      >
        <header className="w-full">
          <p className="bg-slate-300 py-2 text-center text-xs font-normal">
            Embrace Timeless Beauty ✨ Your Adventure, Our Adornments 💍 Every
            Experience Sparkles with Joy
          </p>
          <hgroup className="flex flex-row flex-wrap items-center justify-center px-4 sm:px-8 lg:px-16">
            <div className="flex w-1/2 flex-row items-center justify-start lg:w-1/3">
              <Mail className="mr-2.5 text-stone-500" />{" "}
              <span className="text-xs font-light">Get on the list</span>
            </div>

            <Link href="/" className="w-full lg:w-1/3">
              <h1 className="text-center text-3xl font-medium">App Title</h1>
            </Link>

            <div className="flex w-1/2 flex-row items-center justify-end lg:w-1/3">
              <button className="flex flex-row items-center">
                English <ChevronDown />
              </button>
              <button className="flex flex-row items-center">
                English <ChevronDown />
              </button>
              <Search />
              <ShoppingBag />
            </div>
          </hgroup>
        </header>
        {children}
      </body>
    </html>
  );
}
