import type { Metadata } from "next";
import { Playfair_Display, Outfit } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils";
import { padding } from "@/lib/styles";
import {
  AmericanExpress,
  DinersClub,
  Discover,
  JCB,
  Maestro,
  Mastercard,
  PayPal,
  UnionPay,
  Venmo,
  Visa,
} from "@/components/svg";

const playfair_display = Playfair_Display({
  variable: "--font-playfair-display",
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const outfit = Outfit({
  variable: "--font-outfit",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair_display.variable} ${outfit.variable} bg-slate-50 antialiased`}>
        <Header />
        {children}
        <footer className={cn(padding.x, "flex flex-row items-center justify-between py-24")}>
          <blockquote className="text-sm text-slate-500">
            <p>Copyright © {new Date().getFullYear()} LEGENDA PERMATA</p>
            <Link
              href="https://naufalrabbani.com"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:underline"
            >
              Developed by Naufal Rabbani
            </Link>
          </blockquote>

          <ul className="flex flex-row items-center gap-2">
            {[AmericanExpress, DinersClub, Discover, JCB, Maestro, Mastercard, PayPal, UnionPay, Venmo, Visa].map(
              (Icon, index) => (
                <li key={index}>
                  <Icon />
                </li>
              ),
            )}
          </ul>
        </footer>
      </body>
    </html>
  );
}
